### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by Niemetz** [pfertyk/terraform-templates#1] opened 2024-03-12 01:55 UTC
because there are not nested files under the "content" dir

Error: putting S3 Bucket (john-nguyen-3-11-24-test-website) Policy: operation error S3: PutBucketPolicy, https response error StatusCode: 403, RequestID: RC0EEATWZ0Z41X2C, HostID: F+x7B3rKZ11oInKC7+P11mWNEESmULdWQcrr/wiyK25TQXJ4S1/HeFBFo+cQwkItR4CxwOWHYw0=, api error AccessDenied: Access Denied
│ 
│   with aws_s3_bucket_policy.bucket_policy,
│   on main.tf line 5, in resource "aws_s3_bucket_policy" "bucket_policy":
│    5: resource "aws_s3_bucket_policy" "bucket_policy" {

Thanks
J.N

**Comment by miskatonicstudio** [comment] 2024-03-12 19:41
Thank you for reporting this ;)

I managed to recreate this error locally. I don't believe that it is caused by a nested directory, as I am using this template for a website with a lot of nested resources ;) Also, after removing the nested folder from my local example, I still got this error.

This might have something to do with e.g. different AWS policy resource structure. I will investigate this further.

**Comment by pfertyk** [comment] 2024-03-12 19:42
Thank you for reporting this ;)

I managed to recreate this error locally. I don't believe that it is caused by a nested directory, as I am using this template for a website with a lot of nested resources ;) Also, after removing the nested folder from my local example, I still got this error.

This might have something to do with e.g. different AWS policy resource structure. I will investigate this further.

**Comment by Niemetz** [comment] 2024-03-12 21:47
Hi   Humm.. interesting.  Maybe that the case.  Thank you responding to my inquiry.  John Nguyen
    On Tuesday, March 12, 2024 at 03:42:24 PM EDT, Paweł Fertyk ***@***.***> wrote:  
 
 


Thank you for reporting this ;)

I managed to recreate this error locally. I don't believe that it is caused by a nested directory, as I am using this template for a website with a lot of nested resources ;) Also, after removing the nested folder from my local example, I still got this error.

This might have something to do with e.g. different AWS policy resource structure. I will investigate this further.

**Comment by pfertyk** [comment] 2024-03-18 22:30
Hi @Niemetz ! I think I've solved the problem :) The fix is included in this commit: 30084c5ddfbc53c44be5793715fd947b408c97b5

It seems that an additional resource is required in Terraform to configure a static S3 website. I am sure that the example was working before, so it's was probably changed recently on the AWS side. Either way, the new example should be OK. Could you please check the latest version of this repo to see if it works for you?

**Comment by Niemetz** [comment] 2024-03-18 22:34
Perfect!Thank youJ.N
    On Monday, March 18, 2024 at 06:30:48 PM EDT, Paweł Fertyk ***@***.***> wrote:  
 
 


Hi @Niemetz ! I think I've solved the problem :) The fix is included in this commit: 30084c5

It seems that an additional resource is required in Terraform to configure a static S3 website. I am sure that the example was working before, so it's was probably changed recently on the AWS side. Either way, the new example should be OK. Could you please check the latest version of this repo to see if it works for you?

**Comment by pfertyk** [comment] 2024-06-05 20:22
Hi! I'm closing this issue, since a fix is already provided. If there is still a problem, please feel free to reopen ;)

**Closed as completed by pfertyk** 2024-06-05 20:22 UTC
